### ISSUE TITLE
sumo interprets throws issue when clusters have only one sample

### ISSUE THREAD

**Issue by sienkie** [ratan-lab/sumo#13]
Every label have to be represented in both training and testing set for roc_auc_score function to not throw a following error:
```
(.venv) sienkie@sienkie-asus:~/Desktop/sumo$ sumo interpret tcga_aml/k11/sumo_results.npz expression.flt.tsv.gz,methylation.flt.tsv.gz,mirna.flt.tsv.gz interpreted.tsv
#Loading file: expression.flt.tsv.gz 
Number of dropped rows/features: 0
Number of dropped columns/samples: 0
Data shape: (19183, 173)
#Loading file: methylation.flt.tsv.gz 
Number of dropped rows/features: 224
Number of dropped columns/samples: 0
Data shape: (24757, 194)
#Loading file: mirna.flt.tsv.gz 
Number of dropped rows/features: 1254
Number of dropped columns/samples: 0
Data shape: (330, 188)
#All found features: 44270
Traceback (most recent call last):
  File "/home/sienkie/Desktop/sumo/.venv/bin/sumo", line 11, in <module>
    load_entry_point('python-sumo', 'console_scripts', 'sumo')()
  File "/home/sienkie/Desktop/sumo/src/sumo/run.py", line 12, in main
    mode.run()
  File "/home/sienkie/Desktop/sumo/src/sumo/modes/interpret/interpret.py", line 96, in run
    model = self.create_classifier(x=X, y=labels)
  File "/home/sienkie/Desktop/sumo/src/sumo/modes/interpret/interpret.py", line 152, in create_classifier
    auc = roc_auc_score(y_test, predictions, multi_class='ovr')
  File "/home/sienkie/Desktop/sumo/.venv/lib/python3.6/site-packages/sklearn/metrics/_ranking.py", line 383, in roc_auc_score
    multi_class, average, sample_weight)
  File "/home/sienkie/Desktop/sumo/.venv/lib/python3.6/site-packages/sklearn/metrics/_ranking.py", line 477, in _multiclass_roc_auc_score
    "Number of classes in y_true not equal to the number of "
ValueError: Number of classes in y_true not equal to the number of columns in 'y_score'

```
Here two clusters have only one sample:
```R
> read_tsv('tcga_aml/k11/clusters.tsv') %>% select(label) %>% deframe() %>% table()
 0  1  2  3  4  5  6  7  8  9 10 
13 28 30 26 24 20 20 17 17  1  1 
```
I have [attached](https://github.com/ratan-lab/sumo/files/4216185/k11.zip) sumo_results.npz and clusters.tsv files.

**Comment by aakrosh** [comment]
Should there be a command-line argument to 'sumo interpret' to ensure that the interpretation is only done for a cluster with a minimum number of samples?
